services:
  postgres:
    image: postgres:18.1
    container_name: postgres
    environment:
      POSTGRES_USER: ${PSTG_USER}
      POSTGRES_PASSWORD: ${PSTG_PASSWORD}
      POSTGRES_DB: ${PSTG_DATABASE}
    env_file:
      - .env
    volumes:
      - ./postgre/config.cnf:/etc/postgresql/config.cnf #ARQUIVO POSTGRES_CONFIG.CNF
      - ./postgre/start.sql:/docker-entrypoint-initdb.d/start.sql #ARQUIVO POSTGRES_START.SQL
      - db_data:/var/lib/postgresql #VOLUME DB_POSTGRES
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/config.cnf
    networks:
      - network
  
  quasarbet-api:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: quasarbet-api
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ../projeto/quasarbet-api/:/app
    command: mvn spring-boot:run
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - network

volumes:
  db_data:

networks:
  network:
    driver: bridge