spring.application.name=QuasarBET

#API VERSION
server.servlet.context-path=/api/v1

#SWAGGER
springdoc.api-docs.path=/swagger
springdoc.swagger-ui.disable-swagger-default-url=true

#POSTGRE
spring.datasource.url=jdbc:postgresql://${PSTG_HOST}:${PSTG_PORT}/${PSTG_DATABASE}
spring.datasource.username=${PSTG_USER}
spring.datasource.password=${PSTG_PASSWORD}